### ISSUE TITLE
Updates vs original

### ISSUE THREAD

**Issue by masanasake** [libretro-thumbnails/libretro-thumbnails#111] opened 2022-06-08 15:58 UTC
So in working with particularly Pokemon, I've had a few questions come up. How does everyone feel about updated "fan-art" essentially vs holding true to the original work. Not trying to step on anyone's toes, but recent Pokemon Red was replaced. Generally I'm in favor of some of these clearly updated versions that hold true to the original, but it seems like Red in particular misses the mark: 
<img width="553" alt="image" src="https://user-images.githubusercontent.com/105944840/172660836-ac530fba-b3de-4079-8aea-369699447393.png">
It seems like the colors are muted and everything is so softened up that it doesn't really seem like the same image. This is true especially when compared with Pokemon blue: 
<img width="533" alt="image" src="https://user-images.githubusercontent.com/105944840/172662843-73d7f506-1742-4138-95da-c84b3ad28e2c.png">
The watercolor aspect is gone.

Admittedly, I'm doing something similar (probably from the same place) with Pokemon gen 3, but for a different reason. The holographic/metallic nature of certain covers is really wrecking things, and for these two in particular, it seems like these fan art look closer to the original than the supposed official ones do: 
<img width="337" alt="image" src="https://user-images.githubusercontent.com/105944840/172662067-c0a22906-e4d2-4abb-be3d-11488d7f1a2b.png">
In this case, the "originals" are just so bad in terms of quality and how they appear a much lighter in color vs the holographic/metallic covers that I honestly prefer these "fan-art" ones.

Just seemed like something that needs to be discussed. Any thoughts or ideas would be greatly appreciated.

**Comment by xunkar** [comment] 2022-06-19 10:51
I've managed to salvage some of the original texture for Pokémon Red and included the updated art in the PR. See https://github.com/libretro-thumbnails/Nintendo_-_Game_Boy/pull/73

Now the problem for Red was that the scans were of poor quality, low resolution and riddled with scan artifacts. But any update I work on I always make sure I'm working with the original art, I don't really like repros but sometimes you need a bit of creativity and trickery to make things work (unless you are able to scan the box yourself). Often times I end up recreating lost details. In a way the result is a fan-art, because it's modified, but as long as you do so in the spirit of the original it should be alright.

**Comment by xunkar** [comment] 2022-06-19 10:53
In the case of Ruby & Sapphire for example, I would go for the original because the repros are too different. The backjgrounds have been changed, the black levels are seriously crushed, and the proportions of the Pokémons have been touched.

**Comment by masanasake** [comment] 2022-06-19 13:31
I'm fine with the updated Pokemon Red; really nothing I've found has hit the mark. Ruby and Sapphire I'm also fine with leaving as the "Original", just unfortunate that there's nothing better out there. What do you think of Emerald? Pretty sure in that jaffacakelover pull as well as Rob's attempt to fix it, the metallic version is used. 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/105944840/174483370-a85b7a29-1826-4699-b7c3-949cc3b11b86.png">

I think I'm in favor of the non-metallic one just for consistency and readability, despite how good of a scan it is. (Parappa the Rapper 2 is also the bane of my existence) But in all these cases, I'm not sure where they came from because of the metallic nature, or where everyone sits on the matter.

**Comment by masanasake** [comment] 2022-06-19 13:43
Maybe these are as good as it gets?

![Pokemon - Ruby Version (USA)](https://user-images.githubusercontent.com/105944840/174484092-c12724d0-993b-46a3-8573-e77b67ddfd44.png)
![Pokemon - Sapphire Version (USA)](https://user-images.githubusercontent.com/105944840/174484093-12660566-19c2-474e-8bb0-6a3f23c604a1.png)

**Comment by xunkar** [comment] 2022-06-19 14:04
Those version of Ruby Sapphire are probably the best we can do for now. Too bad the backgrounds have this directional blur kind of effect. But it shouldn't be too difficult to graft the original on those ones, if you want to give it a shot.

For Emerald I think it's a shame to loose the actual *emerald* effect you know what I mean. But holographic/foil cover art are always gonna be a pain to work with no matter what. For what it is I do prefer the original, but I'm also in favor of original covers even if they are not as… hm beautiful as they can be sometimes.

**Comment by masanasake** [comment] 2022-06-19 14:14
My main issue with all these Ruby/Sapphire covers is that they seem like they should be much darker; unless you viewed the original boxes in the brightest room possible, there's no way they'd look like this. These are original... maybe? I'm not sure about "The Pokemon Company" being on it or not, but this seems to be the other extreme of how the boxes would look. Would be nice to find middle ground between the two, but I'll probably just leave it with the higher res ones above, despite a few inconsistencies.
![thumb-1920-37071](https://user-images.githubusercontent.com/105944840/174485383-13876afd-3b16-4142-8b64-270131f9bbdd.jpg)
![thumb-1920-37116](https://user-images.githubusercontent.com/105944840/174485390-7ab0fd85-1a64-4142-966a-3f436abca992.jpg)

**Comment by masanasake** [comment] 2022-06-19 14:48
This one is as good as it gets I think, but still very much imperfect. Illustrates what I meant by two different versions based on lighting.
![pokemon_sapphire_version_with__1636417959_ed895be6](https://user-images.githubusercontent.com/105944840/174486547-3bcd7620-0c8a-4b40-a285-998c6f6d0659.jpg)

From a collection perspective, I think these look very consistent together, and although I'd like to stick as close to the originals as possible, I'd vote to avoid metallic where possible.
<img width="545" alt="image" src="https://user-images.githubusercontent.com/105944840/174486793-9e39d57a-60be-45ae-995c-7661b369b6a2.png">

**Comment by xunkar** [comment] 2022-06-19 15:01
There's no such thing as an ESRB rating in Europe, which tells you that they are US releases. Besides, the Nintendo seal of quality is round in Europe, oval in the US. However, sometimes you can find arts online that have done some mix and match so it's not always an absolute truth. The only reliable source you can get in any case is a genuine box, usually that you can find on websites like ebay and such.

If you consider these two for instances you realize that they are differences that may be attributed to changes during re-releases. https://i.ebayimg.com/images/g/ubsAAOSwFe1f0DUI/s-l640.jpg & https://i.ebayimg.com/images/g/XHMAAOSw8o5fPVmi/s-l640.jpg (don't forget that Ruby & Sapphire had 2 revisions each)

We now know that the art you posted here https://github.com/libretro-thumbnails/libretro-thumbnails/issues/111#issuecomment-1159730592 is actually legit and I have no problem in using that. Of course the ultimate best thing would be to find out which revision used which cover art and match accordingly, but in the meantime I believe we can use this one for every US and European versions without issue.

As for Emerald… the metallic effect is the part of the cover that is holographic/foiled which is why it looks different from Ruby & Sapphire. Besides repro boxes I couldn't find any evidence that a "non-mettalic" version ever existed, so I cannot condone using it, *even if it looks better.* In my opinion the goal of this repo should be aligned with the goal of RetroArch, which is the pristine preservation of retro games. We cannot change the past to make it fit our subjective notions of beauty… However, I'd say that for box art there are compromises that we must make. It can't be helped, it's the nature of restoring something. But when we do have a choice, I do not see a reason to dismiss the original.

**Comment by masanasake** [comment] 2022-06-19 16:15
I think pretty much anything I say at this point is making my argument worse :D , but there was also no non-metallic version of Ruby and Sapphire. Also pretty sure the second box you posted is fake, taken from the fan-made one I originally posted. 
![s-l640](https://user-images.githubusercontent.com/105944840/174490072-835b08da-e3d9-4ac3-84f0-1bd56a9c846a.jpg)

So it seems like if people are fine with the most current Ruby/Sapphire, then Emerald without the metallic should be equally fine. The thing that gets me with that Emerald cover it is it's suspiciously immaculate vs the metallic cover in question. There's also inconsistencies between the "original" 500x500 Pokemon fandom versions of Ruby/Sapphire and the most current higher res ones. But I'm fine with all of these things and respect the Emerald choice ether way. Thanks for your opinion as well as your box art contributions

**Comment by xunkar** [comment] 2022-06-19 16:35
Considering it comes with the cartridge and both booklets, the wear & tear and overall build quality of the box I doubt this is a reproduction, but who knows really. 🤔 

I don't understand your comment about Emerald, I'm sorry.

Also, I'm not the owner of this repo, I'm as much a contributor as you are. I wish there were strong guidelines to help us decide but… I don't think there ever was a pretty strong intent behind this project. It probably just started as "let's collect as many art as we can and serve that as a database for RetroArch." Makes no matter anyway. But today considering the size of the collection, its ties to RetroArch, and the prevalence of RA itself in the field of retro gaming, I feel like it's becoming a necessity.

**Comment by masanasake** [comment] 2022-06-19 17:48
Regarding Pokemon emerald, I was saying the quality was too good for it to be fake. I found where all of these are coming from... and it should have been obvious... Pokemon.com. This is apparently where that weird brown version of the Red box came from as well. 
I'm aware you aren't an owner/admin, just wanted to know your thoughts, and if this changes your mind now that we know the emerald box is official.
![Screenshot_20220619-123932_Samsung Internet](https://user-images.githubusercontent.com/105944840/174493843-26693a89-dfd7-47d5-87ef-d38750b640c8.jpg)
![Screenshot_20220619-124019_Samsung Internet](https://user-images.githubusercontent.com/105944840/174493855-5580369f-3f99-4339-8a4c-3f86d5a58601.jpg)
![Screenshot_20220619-124136_Samsung Internet](https://user-images.githubusercontent.com/105944840/174493858-71ec63c7-5b19-4aba-b39c-002ca0b220c9.jpg)

**Comment by xunkar** [comment] 2022-06-19 17:56
Oh but the fact that Nintendo uses this art today doesn't mean that there ever was a box released with it back then. That's what matters to me anyway. 😅 I mean, otherwise you could just grab a box art for a remaster and use that for its original for instance. Wouldn't seem right to me.

**Closed** 2022-06-25 17:47 UTC
